// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvvmP3yxuYImU8WdKLuTT6TzHUNojzsQc',
    appId: '1:465842792283:web:f90e90b1f5cadbf3e81c7e',
    messagingSenderId: '465842792283',
    projectId: 'game-screen-97060',
    authDomain: 'game-screen-97060.firebaseapp.com',
    storageBucket: 'game-screen-97060.appspot.com',
    measurementId: 'G-Y68BZ7SVQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuFkGSo2XxSWJJ9-I8tJBU-sPzen6rcmo',
    appId: '1:465842792283:android:5852812335ab6dfee81c7e',
    messagingSenderId: '465842792283',
    projectId: 'game-screen-97060',
    storageBucket: 'game-screen-97060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxWQxIRLZpwW98JLvldGboERTV9xi6xt4',
    appId: '1:465842792283:ios:2f31e45edd87344ae81c7e',
    messagingSenderId: '465842792283',
    projectId: 'game-screen-97060',
    storageBucket: 'game-screen-97060.appspot.com',
    iosClientId: '465842792283-hbvv5l63ddhcesr0tid6l5euod076tg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxWQxIRLZpwW98JLvldGboERTV9xi6xt4',
    appId: '1:465842792283:ios:2f31e45edd87344ae81c7e',
    messagingSenderId: '465842792283',
    projectId: 'game-screen-97060',
    storageBucket: 'game-screen-97060.appspot.com',
    iosClientId: '465842792283-hbvv5l63ddhcesr0tid6l5euod076tg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameScreen',
  );
}
